### ISSUE TITLE
[功能请求]请求适配arm架构

### ISSUE THREAD

**Issue by PC12138-Z** [liu23zhi/ESurfingDialerDocker#1]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by liu2-3zhi** [comment]
？？？不能理解你的意思

**Comment by liu2-3zhi** [comment]
你干啥了？？在路由器上拉取了我的镜像？我还没有对arm平台做适配

**Comment by PC12138-Z** [comment]
> 你干啥了？？在路由器上拉取了我的镜像？我还没有对arm平台做适配

麻烦尽快适配一下，原作者的那个，我这边用起来有点抽风，正好看见你这有占用pc端登录的镜像，就试了一下

**Comment by liu2-3zhi** [comment]
由于我目前缺乏对arm的调试经验，适配起来很麻烦，加上我原本就是打算自用的，所以我建议你先试试天翼校园网官方Linux版本客户端，如果不行，后面再寻找时间进行适配。

https://github.com/liu23zhi/ESurfingDialerDocker/blob/2d0783366c7794fb92c61206e4877ff41ddbab58/PC/Get_ESurfingDialerClient.py#L148

**Comment by liu2-3zhi** [comment]
经过努力，已经兼容arm。由于没有arm设备可以测试，还麻烦你测试一下效果。

**Comment by PC12138-Z** [comment]
> 经过努力，已经兼容arm。由于没有arm设备可以测试，还麻烦你测试一下效果。

在我这里使用是有问题的，尝试了一下解决，但是还是报错
![屏幕截图 2024-10-12 015153](https://github.com/user-attachments/assets/94460ddd-58dd-423a-856e-636faa339ef5)

**Comment by liu2-3zhi** [comment]
请先测试phone版本，是我草率了，忘记pc使用了python脚本。

**Comment by PC12138-Z** [comment]
> 请先测试phone版本，是我草率了，忘记pc使用了python脚本。

我按原作者的教程部署了docker，即phone版，我觉得应该跟你的是一样的，所有就没试，等会我试一下

**Comment by PC12138-Z** [comment]
> 请先测试phone版本，是我草率了，忘记pc使用了python脚本。

phone版正常

**Comment by liu2-3zhi** [comment]
感谢反馈，pc版本的问题，我会尽快处理处理的

**Comment by EricZhou05** [comment]
> 由于我目前缺乏对arm的调试经验，适配起来很麻烦，加上我原本就是打算自用的，所以我建议你先试试天翼校园网官方Linux版本客户端，如果不行，后面再寻找时间进行适配。
> 
> https://github.com/liu23zhi/ESurfingDialerDocker/blob/2d0783366c7794fb92c61206e4877ff41ddbab58/PC/Get_ESurfingDialerClient.py#L148

这边官方Linux也不行，一直卡初始化，不知是不是特例，可能要增加测试样本...

![IMG_20241016_101508_733.jpg](https://github.com/user-attachments/assets/596382cf-312f-4988-99a3-3d5fda0a7f0f)

**Comment by EricZhou05** [comment]
很好奇官方Linux版本download链接是怎么被找到的...
ʕ⊝ᴥ⊝ʔ

**Comment by liu2-3zhi** [comment]
> > 由于我目前缺乏对arm的调试经验，适配起来很麻烦，加上我原本就是打算自用的，所以我建议你先试试天翼校园网官方Linux版本客户端，如果不行，后面再寻找时间进行适配。
> > https://github.com/liu23zhi/ESurfingDialerDocker/blob/2d0783366c7794fb92c61206e4877ff41ddbab58/PC/Get_ESurfingDialerClient.py#L148
> 
> 这边官方Linux也不行，一直卡初始化，不知是不是特例，可能要增加测试样本...
> 
> ![IMG_20241016_101508_733.jpg](https://private-user-images.githubusercontent.com/61287015/376861644-596382cf-312f-4988-99a3-3d5fda0a7f0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDU1MDQsIm5iZiI6MTcyOTA0NTIwNCwicGF0aCI6Ii82MTI4NzAxNS8zNzY4NjE2NDQtNTk2MzgyY2YtMzEyZi00OTg4LTk5YTMtM2Q1ZmRhMGE3ZjBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0OWM2MTYxM2FjNmI4YzU0ZDJlOWFkNzBkZWZhMzgyZGZhZjM2ZDJmNjU2MWM4MGZjOWUzZDFiNzkzNTNjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rR6voo-oa9w81Bogg2qrt9_R1tv57SDmNEHGjLGSKts)

我这边反正一切正常

**Comment by liu2-3zhi** [comment]
> 很好奇官方Linux版本download链接是怎么被找到的... ʕ⊝ᴥ⊝ʔ

抓包

**Comment by liu2-3zhi** [comment]
docker镜像还在完善中，可以等我完善之后再测试一下

**Comment by liu2-3zhi** [comment]
经过新一轮适配，pc版本对于arm64的兼容应该没有问题了
不知道 @PC12138-Z 可否方便测试

**Comment by PC12138-Z** [comment]
> 经过新一轮适配，pc版本对于arm64的兼容应该没有问题了 不知道 @PC12138-Z 可否方便测试

好像不行，等明天再研究一下
![屏幕截图 2024-10-20 022101](https://github.com/user-attachments/assets/b915ccec-a1df-403c-9748-cc77b60a28a3)

**Comment by liu2-3zhi** [comment]
> > 经过新一轮适配，pc版本对于arm64的兼容应该没有问题了 不知道 @PC12138-Z 可否方便测试
> 
> 好像不行，等明天再研究一下 ![屏幕截图 2024-10-20 022101](https://private-user-images.githubusercontent.com/148051137/378113469-b915ccec-a1df-403c-9748-cc77b60a28a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTMyNzAsIm5iZiI6MTcyOTM5Mjk3MCwicGF0aCI6Ii8xNDgwNTExMzcvMzc4MTEzNDY5LWI5MTVjY2VjLWExZGYtNDAzYy05NzQ4LWNjNzdiNjBhMjhhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQwMjU2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGVkYjgxNzBjOTBhOWMxMTBiMDJkMmE4ZGRhZmE4YzU5MjhjYWZhZTljMjNiNWMxNWNlNzU4M2I5YzY5ZWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Qur84LzVH2EDK2FH1bJq4nvVjXMZTlANsWlO2FT5qTo)

不是吧，看来我得准备个arm的机子了

**Comment by liu2-3zhi** [comment]
经过长期测试，貌似pc版本无法适配arm。如果硬是要适配，貌似只能内置qemu虚拟机来实现了。
